language: php

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${ILLUMINATE_VERSION}" "phpunit/phpunit:${PHPUNIT_VERSION}"

script:
  - phpunit

matrix:
  include:
    - php: 7.0
      env: ILLUMINATE_VERSION=5.3.*
      env: PHPUNIT_VERSION=~5.4
    - php: 7.0
      env: ILLUMINATE_VERSION=5.4.*
      env: PHPUNIT_VERSION=~5.7
    - php: 7.0
      env: ILLUMINATE_VERSION=5.5.*
      env: PHPUNIT_VERSION=~6.0
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.*
      env: PHPUNIT_VERSION=~6.0
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*
      env: PHPUNIT_VERSION=~7.0
    - php: nightly
      env: ILLUMINATE_VERSION=5.6.*
      env: PHPUNIT_VERSION=~7.0
