language: php

dist: xenial

os: linux

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${ILLUMINATE_VERSION}"

script:
  - composer test

jobs:
  include:
    - php: 7.1
      env:
        - ILLUMINATE_VERSION=5.8.*
    - php: 7.2.24
      env:
        - ILLUMINATE_VERSION=5.8.*
    - php: 7.2.24
      env:
        - ILLUMINATE_VERSION=6.0.*
    - php: 7.2.24
      env:
        - ILLUMINATE_VERSION=7.0.*
    - php: 7.2.24
      env:
        - ILLUMINATE_VERSION=^6.0
    - php: 7.3
      env:
        - ILLUMINATE_VERSION=^6.0
    - php: 7.3
      env:
        - ILLUMINATE_VERSION=^7.0
    - php: 7.4
      env:
        - ILLUMINATE_VERSION=^7.0
